### ISSUE TITLE
SHPC has issues finding user repository

### ISSUE THREAD

**Issue by dipietrantonio** [PawseySC/pawsey-spack-config#231]
```
cdipietrantonio@setonix-03:~> module load shpc/0.1.23 
cdipietrantonio@setonix-03:~> shpc show amdih/pytorch
Traceback (most recent call last):
  File "/software/setonix/2023.08/pawsey/software/shpc/bin/shpc", line 10, in <module>
    sys.exit(run_shpc())
  File "/software/setonix/2023.08/pawsey/software/shpc/lib/python3.10/site-packages/shpc/client/__init__.py", line 556, in run_shpc
    main(args=args, parser=parser, extra=extra, subparser=helper)
  File "/software/setonix/2023.08/pawsey/software/shpc/lib/python3.10/site-packages/shpc/client/show.py", line 13, in main
    cli = get_client(quiet=args.quiet, settings_file=args.settings_file)
  File "/software/setonix/2023.08/pawsey/software/shpc/lib/python3.10/site-packages/shpc/main/__init__.py", line 71, in get_client
    return Client()
  File "/software/setonix/2023.08/pawsey/software/shpc/lib/python3.10/site-packages/shpc/main/modules/lmod.py", line 16, in __init__
    super(Client, self).__init__(**kwargs)
  File "/software/setonix/2023.08/pawsey/software/shpc/lib/python3.10/site-packages/shpc/main/modules/base.py", line 29, in __init__
    super(ModuleBase, self).__init__(**kwargs)
  File "/software/setonix/2023.08/pawsey/software/shpc/lib/python3.10/site-packages/shpc/main/client.py", line 45, in __init__
    self.reload_registry()
  File "/software/setonix/2023.08/pawsey/software/shpc/lib/python3.10/site-packages/shpc/main/client.py", line 57, in reload_registry
    self.registry = registry.Registry(self.settings)
  File "/software/setonix/2023.08/pawsey/software/shpc/lib/python3.10/site-packages/shpc/main/registry/__init__.py", line 45, in __init__
    self.registries = [self.get_registry(r) for r in self.settings.registry]
  File "/software/setonix/2023.08/pawsey/software/shpc/lib/python3.10/site-packages/shpc/main/registry/__init__.py", line 45, in <listcomp>
    self.registries = [self.get_registry(r) for r in self.settings.registry]
  File "/software/setonix/2023.08/pawsey/software/shpc/lib/python3.10/site-packages/shpc/main/registry/__init__.py", line 96, in get_registry
    raise ValueError("No matching registry provider for %s" % source)
ValueError: No matching registry provider for /software/setonix/2023.08/pawsey/software/shpc/lib/python3.10/site-packages/registry
cdipietrantonio@setonix-03:~> 

```

**Comment by dipietrantonio** [comment]
deleted my `~/.singuarity-hpc` and it works
